
language: php

sudo: false

dist: trusty

php:
#  - 5.2 # we cannot run 5.2 because phpunit is installed using composer
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
   - php: nightly

services:
  - memcached
  - mysql

before_script:
    - mysql -e "create database IF NOT EXISTS test;" -uroot

before_install:
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install

script:
   - ./phpunit.sh
